### PR TITLE
removed deprecated class, registering inspections provider

### LINKED ISSUE #21: Not working in newer IntelliJ
Same issue as (inexplicably closed) #20 Plugin does not appear to work with current versions of IntelliJ

The plugin is installed, but CodeNarc does not appear anywhere in IntelliJ except for Plu gins page. And yes, searched everywhere including `inspections`

### PR DESCRIPTION
**Pull request by musketyr**
fixes #21

### CODE REVIEW

**Review by leoroberto — APPROVED** [review]

**Comment by musketyr** [comment]
@demus-nine any chance to get this merged and released anytime soon?

**Comment by luiszimmermann** [comment]
I cant get the build to work in your fix @musketyr, u got this error as well?

```
Caused by: BUG! exception in phase 'semantic analysis' in source unit 'codenarc-idea/src/main/groovy/org/codenarc/idea/CodeNarcComponent.groovy' Invalid index
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:179)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:57)
	at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:80)
	at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:68)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:86)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
	at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:38)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:111)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	... 3 more
Caused by: sun.misc.InvalidJarIndexException: Invalid index
```

**Comment by musketyr** [comment]
I was, but I'm no longer able to run it. I will have to check my other computer. I'll return to the office on Monday so I'll ping you then.

**Comment by musketyr** [comment]
there is an issue in the `ideaIC-LATEST-EAP-SNAPSHOT/lib/proxy-vole-1.0.5-jb.2.jar` JAR file. you can workaround it with setting the version of IntelliJ to some older version such as `2020.3.1`

```
intellij {
    version '2020.3.1'
    pluginName 'CodeNarc'
    downloadSources true
    plugins 'Groovy', 'gradle', 'java'
}
```

**Comment by musketyr** [comment]
I've created also an issue in the IntelliJ's tracker:

https://youtrack.jetbrains.com/issue/IDEA-260882

**Comment by musketyr** [comment]
I'm sorry I forgot to ping you @luiszimmermann that the issue should be fixed now

**Comment by musketyr** [comment]
Any chance to get this PR merged and new version released?

**Comment by musketyr** [comment]
We're happy to take over the maintenance of this project from you @demus-nine if you are no longer interested to move things forward.

**Pull request merged**
